#!/bin/bash
# ============================================================
#  DevSecOps Push Script - Sistema de Inventario
#  Audited & Generated by Antigravity DevSecOps Pipeline
#  Fecha: 2026-05-09
# ============================================================

set -e  # Exit on any error

PROJECT_DIR="/home/daniel_enrique/proyectos/Sistema-de-Inventario-Web-Arquitectura-Escalable-con-Django-y-Docker"
cd "$PROJECT_DIR"

echo "🔒 ===== DevSecOps Pre-Push Pipeline ====="
echo ""

# ----------------------------------------------------------
# PASO 1: Verificar que .env NO se suba
# ----------------------------------------------------------
echo "🛡️  [1/7] Verificando que .env está protegido..."
if git check-ignore .env > /dev/null 2>&1; then
    echo "   ✅ .env está correctamente ignorado por .gitignore"
else
    echo "   ❌ ALERTA: .env NO está siendo ignorado. Abortando."
    exit 1
fi

# ----------------------------------------------------------
# PASO 2: Verificar remoto actualizado
# ----------------------------------------------------------
echo "🌐 [2/7] Verificando remoto..."
REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "NO_REMOTE")
echo "   Remoto actual: $REMOTE_URL"

if echo "$REMOTE_URL" | grep -q "ghp_"; then
    echo "   ❌ ALERTA: Token PAT detectado en la URL del remoto. Abortando."
    exit 1
fi

EXPECTED_URL="https://github.com/Danielperdomo29/Sistema-de-Inventario-Web-Arquitectura-Escalable-con-Django-y-Docker.git"
if [ "$REMOTE_URL" != "$EXPECTED_URL" ]; then
    echo "   ⚠️  Remoto no coincide con el esperado."
    echo "   Esperado: $EXPECTED_URL"
    echo "   Actual:   $REMOTE_URL"
    read -p "   ¿Continuar? (s/n): " -n 1 -r
    echo
    [[ ! $REPLY =~ ^[Ss]$ ]] && exit 1
fi

echo "   ✅ Remoto verificado"

# ----------------------------------------------------------
# PASO 3: Escanear archivos > 50MB
# ----------------------------------------------------------
echo "📏 [3/7] Escaneando archivos > 50MB (excluyendo .git y venv)..."
LARGE_FILES=$(find . -maxdepth 4 -size +50M \
    -not -path "./.git/*" \
    -not -path "./venv/*" \
    -not -path "./.docker/mysql/database/*" \
    2>/dev/null || true)

if [ -n "$LARGE_FILES" ]; then
    echo "   ⚠️  ARCHIVOS GRANDES DETECTADOS:"
    echo "$LARGE_FILES" | while read -r f; do
        SIZE=$(du -h "$f" 2>/dev/null | cut -f1)
        echo "   📁 $f ($SIZE)"
    done
    echo ""
    read -p "   ¿Continuar sin estos archivos? (s/n): " -n 1 -r
    echo
    [[ ! $REPLY =~ ^[Ss]$ ]] && exit 1
else
    echo "   ✅ No se encontraron archivos > 50MB"
fi

# ----------------------------------------------------------
# PASO 4: Escaneo de secretos en archivos tracked
# ----------------------------------------------------------
echo "🔍 [4/7] Escaneando secretos hardcodeados en archivos Python..."
SECRET_LEAKS=0

# Buscar API keys hardcodeadas (no en .env ni .env.example)
if grep -rn "AIzaSy\|sk-or-v1-\|sk-bbb\|GOCSPX-" \
    --include="*.py" --include="*.yml" --include="*.yaml" \
    --exclude-dir=venv --exclude-dir=.git . 2>/dev/null; then
    echo "   ⚠️  Se encontraron posibles API keys en el código fuente"
    SECRET_LEAKS=1
fi

if [ $SECRET_LEAKS -eq 0 ]; then
    echo "   ✅ No se detectaron secretos hardcodeados"
fi

# ----------------------------------------------------------
# PASO 5: Limpiar cache antes del staging
# ----------------------------------------------------------
echo "🧹 [5/7] Limpiando archivos de cache..."
find . -type d -name "__pycache__" -not -path "./venv/*" -exec rm -rf {} + 2>/dev/null || true
find . -name "*.pyc" -not -path "./venv/*" -delete 2>/dev/null || true
echo "   ✅ Cache limpiada"

# ----------------------------------------------------------
# PASO 6: Stage y Commit
# ----------------------------------------------------------
echo "📝 [6/7] Preparando commit..."

# Limpiar el index de archivos que ahora están en .gitignore
git rm -r --cached __pycache__/ 2>/dev/null || true
git rm --cached .coverage 2>/dev/null || true
git rm --cached celerybeat-schedule 2>/dev/null || true
git rm --cached server.log 2>/dev/null || true
git rm --cached bandit-report.json 2>/dev/null || true
git rm --cached bandit_project_high.json 2>/dev/null || true
git rm --cached bandit_project_medium.json 2>/dev/null || true
git rm --cached all_templates.txt 2>/dev/null || true
git rm --cached debug_hash.txt 2>/dev/null || true
git rm --cached test_git.txt 2>/dev/null || true
git rm -r --cached scratch/ 2>/dev/null || true
git rm -r --cached venv/ 2>/dev/null || true
git rm --cached .env 2>/dev/null || true

# Stage todos los archivos (respetando .gitignore)
git add -A

# Mostrar resumen
echo ""
echo "   📊 Resumen de cambios:"
git diff --cached --stat | tail -5
echo ""
STAGED_COUNT=$(git diff --cached --name-only | wc -l)
echo "   Total archivos en staging: $STAGED_COUNT"

# Commit
git commit -m "Feat: Initial architecture with Django and Docker - Scalable Inventory System

- Django 5.x + MySQL 8.0 + Redis 7 architecture
- Docker Compose multi-service (web, db, redis, celery worker, celery beat)
- Phase 5: AllAuth + 2FA + Google OAuth integration
- DIAN Factus electronic invoicing module
- EventBus + DataAggregator infrastructure (core)
- AI Chatbot RAG + Analytics ML modules
- OWASP security headers + CSP + CORS
- Argon2 password hashing + rate limiting
- DevSecOps: .gitignore hardened, secrets in .env only
- CI/CD: GitHub Actions + GitLab CI pipelines"

echo "   ✅ Commit creado exitosamente"

# ----------------------------------------------------------
# PASO 7: Push a main
# ----------------------------------------------------------
echo "🚀 [7/7] Pushing to main..."
echo "   ⚠️  Se te pedirá autenticación (GitHub credential manager)"
echo ""

git push -u origin main

echo ""
echo "============================================================"
echo "🎉 ¡PUSH COMPLETADO EXITOSAMENTE!"
echo "============================================================"
echo "📦 Repositorio: https://github.com/Danielperdomo29/Sistema-de-Inventario-Web-Arquitectura-Escalable-con-Django-y-Docker"
echo "🌿 Rama: main"
echo ""
echo "📋 RECOMENDACIONES POST-PUSH:"
echo "   1. Rota el PAT de GitHub que estaba en .git/config"
echo "   2. Genera un SECRET_KEY criptográfico para producción:"
echo "      python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
echo "   3. Verifica en GitHub que .env NO aparezca en el repo"
echo "   4. Al migrar al NVMe 2TB, solo ejecuta:"
echo "      git clone https://github.com/Danielperdomo29/Sistema-de-Inventario-Web-Arquitectura-Escalable-con-Django-y-Docker.git"
echo "      cd Sistema-de-Inventario-Web-Arquitectura-Escalable-con-Django-y-Docker"
echo "      cp .env.example .env  # Editar con tus credenciales"
echo "      docker-compose up -d  # ¡Listo!"
echo "============================================================"
