# Generated by Django 5.2.9 on 2025-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_client_role_supplier_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tax_included',
            field=models.BooleanField(default=False, verbose_name='Impuesto incluido en precio'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Porcentaje Impuesto'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_type_id',
            field=models.CharField(default='01', max_length=4, verbose_name='Código Impuesto DIAN'),
        ),
    ]
