# Generated by Django 6.0 on 2025-12-24 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_is_tax_included_product_tax_percentage_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el email ha sido verificado (allauth)'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de verificación del email', null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación (CC, NIT, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Última vez que cambió la contraseña', null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='use_allauth',
            field=models.BooleanField(default=False, help_text='Usuario migrado al nuevo sistema de autenticación con allauth'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['email_verified'], name='auth_user_email_v_2019f3_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['use_allauth'], name='auth_user_use_all_10a5bd_idx'),
        ),
    ]
