# Generated by Django 6.0 on 2026-01-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chatbotmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_tax_declarant',
            field=models.BooleanField(default=False, help_text='Marque si el proveedor es declarante de renta (afecta tarifas de retención)', verbose_name='Es declarante de renta'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='retention_concepts',
            field=models.JSONField(blank=True, default=list, help_text='Lista de conceptos de retención que aplican a este proveedor', verbose_name='Conceptos de retención aplicables'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='retention_responsibility',
            field=models.CharField(choices=[('RESPONSABLE', 'Responsable de IVA'), ('NO_RESPONSABLE', 'No responsable de IVA'), ('SIMPLIFICADO', 'Régimen simplificado'), ('EXENTO', 'Exento')], default='RESPONSABLE', max_length=50, verbose_name='Responsabilidad de retención'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_identification_type',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('EXTRANJERIA', 'Cédula de extranjería')], default='NIT', max_length=20, verbose_name='Tipo de identificación tributaria'),
        ),
    ]
