# Generated by Django 6.0 on 2026-01-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_supplier_is_tax_declarant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='iva_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de IVA', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal sin IVA', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='iva_tasa',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Tasa de IVA (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='iva_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del IVA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='subtotal_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal sin IVA (cantidad * precio_unitario)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario SIN IVA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal CON IVA (subtotal_sin_iva + iva_valor)', max_digits=12),
        ),
    ]
