# Generated by Django 6.0 on 2026-01-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_populate_tax_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='ruc',
        ),
        migrations.AddField(
            model_name='supplier',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='digito_verificacion',
            field=models.CharField(blank=True, help_text='Dígito de verificación del NIT', max_length=1, null=True, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nit',
            field=models.CharField(blank=True, help_text='Número de Identificación Tributaria (sin dígito de verificación)', max_length=15, null=True, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rut',
            field=models.CharField(blank=True, help_text='Registro Único Tributario', max_length=50, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
