# Generated by Django 6.0 on 2026-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_nit_rut_to_supplier'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['documento'], name='idx_client_documento'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='idx_client_email'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['activo'], name='idx_client_activo'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['codigo'], name='idx_prod_codigo'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['categoria'], name='idx_prod_categoria'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['activo'], name='idx_prod_activo'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_actual'], name='idx_prod_stock'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['activo', 'stock_actual'], name='idx_prod_activo_stock'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['fecha'], name='idx_sale_fecha'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cliente'], name='idx_sale_cliente'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['usuario'], name='idx_sale_usuario'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['estado'], name='idx_sale_estado'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-fecha', 'estado'], name='idx_sale_fecha_estado'),
        ),
    ]
