# Generated by Django 6.0 on 2026-01-06 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_client_idx_client_documento_client_idx_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='auto_extracted',
            field=models.BooleanField(default=False, help_text='Indica si el total fue extraído con OCR', verbose_name='Extraído automáticamente'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='extracted_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto extraído automáticamente de la factura', max_digits=12, null=True, verbose_name='Total extraído (OCR)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='extraction_confidence',
            field=models.FloatField(blank=True, help_text='Nivel de confianza del OCR (0.0 a 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza de extracción'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='extraction_log',
            field=models.TextField(blank=True, help_text='Datos técnicos de la extracción OCR (JSON)', null=True, verbose_name='Log de extracción'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt_file',
            field=models.CharField(blank=True, help_text='Ruta relativa del archivo PDF o imagen de la factura', max_length=255, null=True, verbose_name='Ruta del archivo de factura'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('image', 'Imagen')], max_length=10, null=True, verbose_name='Tipo de archivo'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de carga de la factura', null=True, verbose_name='Fecha de carga'),
        ),
    ]
