# Generated by Django 6.0 on 2026-01-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_receipt_ocr_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('STOCK_CRITICO', 'Stock Crítico (Sin Stock)'), ('STOCK_BAJO', 'Stock Bajo'), ('PRODUCTO_LENTO', 'Producto de Baja Rotación'), ('VENCIMIENTO_PROXIMO', 'Vencimiento Próximo'), ('MARGEN_BAJO', 'Margen de Ganancia Bajo'), ('ANOMALIA_PRECIO', 'Anomalía en Precio')], db_index=True, max_length=30)),
                ('nivel', models.CharField(choices=[('ROJO', 'Urgente'), ('AMARILLO', 'Atención'), ('VERDE', 'Informativo')], db_index=True, default='AMARILLO', max_length=10)),
                ('mensaje', models.TextField(help_text='Descripción de la alerta')),
                ('accion_sugerida', models.TextField(blank=True, help_text='Recomendación de acción (puede ser generada por IA)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADA', 'Revisada'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], db_index=True, default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id', help_text='Producto relacionado (opcional para alertas globales)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app.product')),
            ],
            options={
                'verbose_name': 'Alerta Automática',
                'verbose_name_plural': 'Alertas Automáticas',
                'db_table': 'alertas_automaticas',
                'ordering': ['-nivel', '-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'nivel', '-fecha_creacion'], name='idx_alert_estado_nivel'), models.Index(fields=['producto', 'tipo_alerta'], name='idx_alert_prod_tipo'), models.Index(fields=['tipo_alerta', 'estado'], name='idx_alert_tipo_estado')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('producto', 'tipo_alerta', 'estado'), name='unique_pending_alert_per_product')],
            },
        ),
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('ajuste', 'Ajuste Manual'), ('devolucion', 'Devolución'), ('merma', 'Merma/Pérdida')], db_index=True, max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento (positivo o negativo)')),
                ('stock_anterior', models.IntegerField(help_text='Stock antes del movimiento')),
                ('stock_nuevo', models.IntegerField(help_text='Stock después del movimiento')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del movimiento (venta_id, compra_id, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='historial_movimientos', to='app.product')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historial de Stock',
                'db_table': 'historial_stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['producto', '-created_at'], name='idx_hist_prod_fecha'), models.Index(fields=['tipo_movimiento', '-created_at'], name='idx_hist_tipo_fecha'), models.Index(fields=['-created_at'], name='idx_hist_fecha')],
            },
        ),
    ]
