# Generated by Django 6.0 on 2026-01-12 16:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_stock_tracking_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha del snapshot de KPIs')),
                ('unidades_vendidas', models.IntegerField(default=0, help_text='Total de unidades vendidas en la fecha', validators=[django.core.validators.MinValueValidator(0)])),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia total generada (precio_venta - precio_compra) * cantidad', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('margen_promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Margen de ganancia promedio en porcentaje (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rotacion_dias', models.IntegerField(blank=True, help_text='Días promedio de rotación del inventario', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('velocidad_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unidades vendidas por día (promedio últimos 30 días)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ranking_abc', models.CharField(blank=True, choices=[('A', 'Clase A - 20% productos que generan 80% ganancias'), ('B', 'Clase B - 30% productos siguientes'), ('C', 'Clase C - 50% productos restantes')], help_text='Clasificación ABC según análisis de Pareto', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('producto', models.ForeignKey(help_text='Producto al que pertenecen estos KPIs', on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='app.product')),
            ],
            options={
                'verbose_name': 'KPI de Producto',
                'verbose_name_plural': 'KPIs de Productos',
                'db_table': 'kpi_productos',
                'ordering': ['-fecha', '-unidades_vendidas'],
                'indexes': [models.Index(fields=['producto', 'fecha'], name='idx_kpi_producto_fecha'), models.Index(fields=['fecha', 'ranking_abc'], name='idx_kpi_fecha_abc'), models.Index(fields=['-unidades_vendidas'], name='idx_kpi_top_vendidos'), models.Index(fields=['-ganancia_total'], name='idx_kpi_top_ganancias'), models.Index(fields=['rotacion_dias'], name='idx_kpi_rotacion')],
                'unique_together': {('producto', 'fecha')},
            },
        ),
    ]
