# Generated by Django 6.0 on 2026-04-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_kpi_producto_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración por defecto', max_length=100)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=20)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=20)),
                ('welcome_title', models.CharField(default='PayRoll', max_length=200)),
                ('welcome_subtitle', models.CharField(default='Fill in your details to get started', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ui/logos/')),
                ('footer_text', models.CharField(default='Free 14-day trial • No credit card required • Cancel anytime', max_length=500)),
                ('enable_social_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de UI',
                'verbose_name_plural': 'Configuraciones de UI',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ui/backgrounds/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ui_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_images', to='app.uiconfig')),
            ],
            options={
                'verbose_name': 'Imagen de Fondo',
                'verbose_name_plural': 'Imágenes de Fondo',
                'ordering': ['order'],
            },
        ),
    ]
