# Generated by Django 5.0.14 on 2026-04-28 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_uiconfig_backgroundimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Identificador público seguro para URLs y APIs (previene IDOR)",
                unique=True,
            ),
        ),
    ]
