# Generated by Django 5.0.14 on 2026-05-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_useraccount_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="public_id",
        ),
    ]
