# Generated by Django 5.0.14 on 2026-05-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_useraccount_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="codigo_dian",
            field=models.CharField(
                blank=True, help_text="Código estándar DIAN (ej. UNSPSC)", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="iva_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=19.0, max_digits=5, verbose_name="Porcentaje de IVA"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="iva_tipo",
            field=models.CharField(
                choices=[("GRAVADO", "Gravado"), ("EXENTO", "Exento"), ("EXCLUIDO", "Excluido")],
                default="GRAVADO",
                max_length=10,
                verbose_name="Tipo de IVA",
            ),
        ),
        migrations.AlterField(
            model_name="saledetail",
            name="iva_valor",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="Valor del IVA", max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="saledetail",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total de la línea (Subtotal sin IVA + IVA Valor)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="saledetail",
            name="subtotal_sin_iva",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base Gravable x Cantidad",
                max_digits=12,
                null=True,
            ),
        ),
    ]
