# Generated by Django 5.0.14 on 2026-05-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_product_codigo_dian_product_iva_porcentaje_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="impoconsumo",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Impoconsumo (%)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unidad_medida",
            field=models.CharField(default="94", max_length=5, verbose_name="Unidad de Medida"),
        ),
    ]
