# Generated by Django 5.0.14 on 2026-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_product_impoconsumo_product_unidad_medida"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje de descuento por defecto (%)",
                max_digits=5,
            ),
        ),
    ]
