# Generated by Django 5.0.14 on 2026-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_product_descuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="saledetail",
            name="descuento_tasa",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="saledetail",
            name="descuento_valor",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
