# Generated by Django 5.2.9 on 2025-12-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_category_client_role_supplier_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDIAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número oficial de facturación (Prefijo + Consecutivo)', max_length=50, unique=True)),
                ('cufe', models.CharField(blank=True, help_text='Código Único de Facturación Electrónica', max_length=150, null=True)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='dian/xml/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='dian/pdf/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generada', 'Generada'), ('enviada', 'Enviada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura_dian', to='app.sale')),
            ],
            options={
                'verbose_name': 'Factura DIAN',
                'verbose_name_plural': 'Facturas DIAN',
                'db_table': 'facturas_dian',
            },
        ),
    ]
