# Generated by Django 6.0 on 2025-12-26 10:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_useraccount_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único de la cuenta', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la cuenta', max_length=200)),
                ('nivel', models.IntegerField(help_text='Nivel jerárquico (1-5)')),
                ('naturaleza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], help_text='Naturaleza de la cuenta (Débito o Crédito)', max_length=1)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo')], help_text='Tipo de cuenta', max_length=20)),
                ('acepta_movimiento', models.BooleanField(default=False, help_text='Indica si la cuenta puede tener movimientos contables')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la cuenta está activa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la cuenta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('padre', models.ForeignKey(blank=True, help_text='Cuenta padre en la jerarquía', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='fiscal.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'cuenta_contable',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FiscalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('EXPORT', 'Exportar')], db_index=True, help_text='Tipo de acción realizada', max_length=10)),
                ('model_name', models.CharField(db_index=True, help_text='Nombre del modelo afectado', max_length=100)),
                ('object_id', models.CharField(db_index=True, help_text='ID del objeto afectado', max_length=100)),
                ('user_ip', models.GenericIPAddressField(help_text='Dirección IP del usuario')),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Momento exacto de la acción')),
                ('old_values', models.JSONField(blank=True, help_text='Valores anteriores (para UPDATE/DELETE)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Valores nuevos (para CREATE/UPDATE)', null=True)),
                ('changes', models.JSONField(blank=True, help_text='Cambios específicos con old/new', null=True)),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión', max_length=100)),
                ('request_path', models.CharField(blank=True, help_text='Ruta de la petición HTTP', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='Método HTTP (GET, POST, etc.)', max_length=10)),
                ('success', models.BooleanField(default=True, help_text='Si la operación fue exitosa')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría Fiscal',
                'verbose_name_plural': 'Registros de Auditoría Fiscal',
                'db_table': 'fiscal_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del impuesto', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del impuesto', max_length=100)),
                ('tipo', models.CharField(choices=[('IVA', 'IVA'), ('RETEFUENTE', 'Retención en la Fuente'), ('RETEIVA', 'Retención de IVA'), ('RETEICA', 'Retención de ICA')], help_text='Tipo de impuesto', max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto (ej: 19.00 para 19%)', max_digits=5)),
                ('base_minima', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base mínima para aplicar el impuesto', max_digits=15)),
                ('aplica_compras', models.BooleanField(default=False, help_text='Indica si el impuesto aplica en compras')),
                ('aplica_ventas', models.BooleanField(default=False, help_text='Indica si el impuesto aplica en ventas')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el impuesto está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('cuenta_por_cobrar', models.ForeignKey(blank=True, help_text='Cuenta contable para el impuesto por cobrar (retenciones)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_por_cobrar', to='fiscal.cuentacontable')),
                ('cuenta_por_pagar', models.ForeignKey(help_text='Cuenta contable para el impuesto por pagar', on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_por_pagar', to='fiscal.cuentacontable')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'impuesto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PerfilFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('13', 'Cédula de Ciudadanía'), ('22', 'Cédula de Extranjería'), ('31', 'NIT'), ('41', 'Pasaporte'), ('42', 'Documento de Identificación Extranjero')], help_text='Tipo de documento de identificación', max_length=2)),
                ('numero_documento', models.CharField(help_text='Número de identificación tributaria', max_length=20)),
                ('dv', models.CharField(blank=True, help_text='Dígito verificador (auto-calculado para NIT)', max_length=1)),
                ('tipo_persona', models.CharField(choices=[('J', 'Jurídica'), ('N', 'Natural')], help_text='Tipo de persona (Jurídica o Natural)', max_length=1)),
                ('responsabilidades', models.JSONField(blank=True, default=list, help_text='Lista de responsabilidades tributarias (ej: ["O-13", "O-15"])')),
                ('regimen', models.CharField(choices=[('48', 'Responsable de IVA'), ('49', 'No responsable de IVA')], help_text='Régimen tributario', max_length=2)),
                ('departamento_codigo', models.CharField(help_text='Código DANE del departamento (2 dígitos)', max_length=2)),
                ('municipio_codigo', models.CharField(help_text='Código DANE del municipio (3 dígitos)', max_length=3)),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre comercial (opcional)', max_length=200)),
                ('actividad_economica', models.CharField(blank=True, help_text='Código CIIU de actividad económica (4 dígitos)', max_length=4)),
                ('email_facturacion', models.EmailField(help_text='Email para envío de facturas electrónicas', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('direccion', models.TextField(help_text='Dirección fiscal completa')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el perfil está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del perfil')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('cliente', models.OneToOneField(blank=True, help_text='Cliente asociado a este perfil fiscal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_fiscal', to='app.client')),
                ('proveedor', models.OneToOneField(blank=True, help_text='Proveedor asociado a este perfil fiscal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_fiscal', to='app.supplier')),
            ],
            options={
                'verbose_name': 'Perfil Fiscal',
                'verbose_name_plural': 'Perfiles Fiscales',
                'db_table': 'perfil_fiscal',
            },
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['codigo'], name='cuenta_cont_codigo_7a5af7_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['nivel'], name='cuenta_cont_nivel_52f794_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['tipo'], name='cuenta_cont_tipo_92d5de_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalauditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='fiscal_audi_model_n_d58d44_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='fiscal_audi_user_id_d25dde_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='fiscal_audi_action_d59e72_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalauditlog',
            index=models.Index(fields=['timestamp'], name='fiscal_audi_timesta_aac34c_idx'),
        ),
        migrations.AddIndex(
            model_name='impuesto',
            index=models.Index(fields=['codigo'], name='impuesto_codigo_4380b5_idx'),
        ),
        migrations.AddIndex(
            model_name='impuesto',
            index=models.Index(fields=['tipo'], name='impuesto_tipo_87adc9_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilfiscal',
            index=models.Index(fields=['numero_documento'], name='perfil_fisc_numero__634a67_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilfiscal',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='perfil_fisc_tipo_do_d44b31_idx'),
        ),
    ]
