# Generated by Django 6.0 on 2025-12-31 22:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.BigIntegerField(db_index=True, help_text='Número consecutivo único e inviolable', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_contable', models.DateField(db_index=True, help_text='Fecha del hecho económico (no modificable después de creación)')),
                ('sello_temporal', models.DateTimeField(auto_now_add=True, help_text='Timestamp exacto de creación (no repudio)')),
                ('tipo_asiento', models.CharField(choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste Contable'), ('CIERRE', 'Cierre de Período'), ('APERTURA', 'Apertura de Período'), ('NOMINA', 'Nómina'), ('MANUAL', 'Manual')], db_index=True, help_text='Tipo de asiento contable', max_length=10)),
                ('documento_origen_tipo', models.CharField(blank=True, help_text='Tipo de documento origen (FACTURA, RECIBO, NOTA, etc.)', max_length=20)),
                ('documento_origen_numero', models.CharField(blank=True, db_index=True, help_text='Número del documento origen', max_length=50)),
                ('tercero_nit', models.CharField(blank=True, db_index=True, help_text='NIT del tercero relacionado', max_length=20)),
                ('tercero_nombre', models.CharField(blank=True, help_text='Nombre del tercero', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del asiento (mínimo 10 caracteres)')),
                ('total_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma total de débitos', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma total de créditos', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diferencia (debe ser 0.00 para asientos válidos)', max_digits=15)),
                ('hash_integridad', models.CharField(db_index=True, editable=False, help_text='SHA-256 del asiento completo (incluye detalles)', max_length=64)),
                ('firma_digital', models.TextField(blank=True, help_text='Firma digital para asientos críticos (>$10M)')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='IP desde donde se creó el asiento', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Navegador/sistema del usuario', max_length=255)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], db_index=True, default='BORRADOR', help_text='Estado del asiento', max_length=10)),
                ('fecha_anulacion', models.DateTimeField(blank=True, help_text='Fecha de anulación', null=True)),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Motivo de la anulación (obligatorio si anulado)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_anulacion', models.ForeignKey(blank=True, help_text='Usuario que anuló el asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_anulados', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(help_text='Usuario que creó el asiento', on_delete=django.db.models.deletion.PROTECT, related_name='asientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'contabilidad_asiento',
                'ordering': ['-numero_asiento'],
                'permissions': [('anular_asiento', 'Puede anular asientos contables'), ('cerrar_periodo', 'Puede cerrar períodos contables'), ('ver_asientos_todos', 'Puede ver todos los asientos'), ('firmar_asiento', 'Puede firmar asientos digitalmente')],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(help_text='Año del período', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes del período (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del período')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='ABIERTO', help_text='Estado del período', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora del cierre', null=True)),
                ('hash_cierre', models.CharField(blank=True, db_index=True, help_text='SHA-256 de todos los asientos del período', max_length=64)),
                ('total_asientos', models.PositiveIntegerField(default=0, help_text='Total de asientos en el período')),
                ('total_debitos', models.DecimalField(decimal_places=2, default=0, help_text='Suma total de débitos del período', max_digits=18)),
                ('total_creditos', models.DecimalField(decimal_places=2, default=0, help_text='Suma total de créditos del período', max_digits=18)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del cierre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_cierre', models.ForeignKey(blank=True, help_text='Usuario que cerró el período', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período Contable',
                'verbose_name_plural': 'Períodos Contables',
                'db_table': 'contabilidad_periodo',
                'ordering': ['-año', '-mes'],
                'permissions': [('cerrar_periodo_contable', 'Puede cerrar períodos contables'), ('reabrir_periodo_contable', 'Puede reabrir períodos cerrados')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoriaContable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp exacto del evento')),
                ('tipo_evento', models.CharField(choices=[('CREACION_ASIENTO', 'Creación de Asiento'), ('MODIFICACION_ASIENTO', 'Modificación de Asiento'), ('ANULACION_ASIENTO', 'Anulación de Asiento'), ('CIERRE_PERIODO', 'Cierre de Período'), ('REAPERTURA_PERIODO', 'Reapertura de Período'), ('ACCESO_CONTABILIDAD', 'Acceso al Módulo Contable'), ('CONSULTA_ASIENTO', 'Consulta de Asiento'), ('EXPORTACION_DATOS', 'Exportación de Datos'), ('INTENTO_ACCESO_NO_AUTORIZADO', 'Intento de Acceso No Autorizado'), ('MODIFICACION_PERIODO_CERRADO', 'Intento de Modificar Período Cerrado'), ('DESCUADRE_DETECTADO', 'Descuadre Contable Detectado'), ('ANOMALIA_DETECTADA', 'Anomalía Detectada'), ('VERIFICACION_INTEGRIDAD', 'Verificación de Integridad'), ('DISCREPANCIA_HASH', 'Discrepancia de Hash Detectada')], db_index=True, help_text='Tipo de evento auditado', max_length=50)),
                ('usuario_nombre', models.CharField(help_text='Nombre del usuario (desnormalizado para histórico)', max_length=150)),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.CharField(blank=True, default='', help_text='Navegador/sistema del usuario', max_length=255)),
                ('endpoint', models.CharField(blank=True, default='', help_text='Endpoint/URL accedido', max_length=255)),
                ('metodo_http', models.CharField(blank=True, default='', help_text='Método HTTP (GET, POST, etc.)', max_length=10)),
                ('detalles', models.JSONField(default=dict, help_text='Detalles adicionales del evento (JSON)')),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('BLOQUEADO', 'Bloqueado'), ('ADVERTENCIA', 'Advertencia')], db_index=True, default='EXITOSO', help_text='Resultado de la operación', max_length=15)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error (si aplica)')),
                ('severidad', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], db_index=True, default='INFO', help_text='Nivel de severidad', max_length=10)),
                ('asiento', models.ForeignKey(blank=True, help_text='Asiento afectado (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to='fiscal.asientocontable')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.PROTECT, related_name='logs_contables', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, help_text='Período afectado (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to='fiscal.periodocontable')),
            ],
            options={
                'verbose_name': 'Log de Auditoría Contable',
                'verbose_name_plural': 'Logs de Auditoría Contable',
                'db_table': 'contabilidad_log_auditoria',
                'ordering': ['-timestamp'],
                'permissions': [('ver_logs_auditoria', 'Puede ver logs de auditoría'), ('exportar_logs_auditoria', 'Puede exportar logs de auditoría')],
            },
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='periodo_contable',
            field=models.ForeignKey(blank=True, help_text='Período contable al que pertenece', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='fiscal.periodocontable'),
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de la línea en el asiento')),
                ('debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del débito', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del crédito', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descripcion_detalle', models.CharField(help_text='Descripción específica de esta línea', max_length=500)),
                ('centro_costo', models.CharField(blank=True, help_text='Centro de costos (si aplica)', max_length=20)),
                ('tercero_nit', models.CharField(blank=True, help_text='NIT del tercero específico de esta línea', max_length=20)),
                ('tercero_nombre', models.CharField(blank=True, help_text='Nombre del tercero', max_length=200)),
                ('hash_linea', models.CharField(db_index=True, editable=False, help_text='SHA-256 de esta línea específica', max_length=64)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Última modificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(help_text='Asiento contable al que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='fiscal.asientocontable')),
                ('cuenta_contable', models.ForeignKey(help_text='Cuenta contable del PUC', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='fiscal.cuentacontable')),
                ('usuario_modificacion', models.ForeignKey(blank=True, help_text='Último usuario que modificó esta línea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Detalles de Asientos',
                'db_table': 'contabilidad_detalle_asiento',
                'ordering': ['asiento', 'orden'],
                'indexes': [models.Index(fields=['asiento', 'orden'], name='contabilida_asiento_ab966c_idx'), models.Index(fields=['cuenta_contable', 'asiento'], name='contabilida_cuenta__821d02_idx'), models.Index(fields=['hash_linea'], name='contabilida_hash_li_a62f79_idx')],
                'unique_together': {('asiento', 'orden')},
            },
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['año', 'mes'], name='contabilida_año_6be3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['estado'], name='contabilida_estado_883dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='contabilida_fecha_i_7382c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodocontable',
            unique_together={('año', 'mes')},
        ),
        migrations.AddIndex(
            model_name='logauditoriacontable',
            index=models.Index(fields=['-timestamp'], name='contabilida_timesta_41a96c_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoriacontable',
            index=models.Index(fields=['tipo_evento', '-timestamp'], name='contabilida_tipo_ev_b4eb58_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoriacontable',
            index=models.Index(fields=['usuario', '-timestamp'], name='contabilida_usuario_a23b77_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoriacontable',
            index=models.Index(fields=['resultado', 'severidad'], name='contabilida_resulta_58e671_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoriacontable',
            index=models.Index(fields=['asiento'], name='contabilida_asiento_b80d03_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoriacontable',
            index=models.Index(fields=['periodo'], name='contabilida_periodo_0ea314_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['numero_asiento'], name='contabilida_numero__705b22_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha_contable', 'tipo_asiento'], name='contabilida_fecha_c_8b61f7_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['estado', 'fecha_contable'], name='contabilida_estado_0ed081_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['documento_origen_tipo', 'documento_origen_numero'], name='contabilida_documen_d2c18e_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['hash_integridad'], name='contabilida_hash_in_f4e52c_idx'),
        ),
    ]
