# Generated by Django 6.0 on 2026-01-01 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_useraccount_email_verified_and_more'),
        ('fiscal', '0002_asientocontable_periodocontable_logauditoriacontable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cufe', models.CharField(blank=True, max_length=96, null=True, unique=True, verbose_name='Código Único de Factura Electrónica')),
                ('qrcode', models.TextField(blank=True, null=True, verbose_name='Datos QR')),
                ('xml_firmado', models.FileField(blank=True, null=True, upload_to='fiscal/xml/firmados/%Y/%m/', verbose_name='XML Firmado')),
                ('xml_respuesta_dian', models.FileField(blank=True, null=True, upload_to='fiscal/xml/respuestas/%Y/%m/', verbose_name='ApplicationResponse DIAN')),
                ('estado_dian', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('GENERADO', 'XML Generado'), ('FIRMADO', 'XML Firmado'), ('ENVIADO', 'Enviado a DIAN'), ('ACEPTADO', 'Aceptado por DIAN'), ('RECHAZADO', 'Rechazado por DIAN'), ('ERROR', 'Error Técnico')], db_index=True, default='PENDIENTE', max_length=20)),
                ('ambiente', models.IntegerField(choices=[(1, 'Producción'), (2, 'Pruebas')], default=2, verbose_name='Ambiente de Habilitación')),
                ('fecha_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Emisión (Firma)')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Envío DIAN')),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura_electronica', to='app.sale', verbose_name='Venta asociada')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'db_table': 'fiscal_factura_electronica',
                'permissions': [('emitir_factura_electronica', 'Puede emitir facturas electrónicas'), ('consultar_estado_dian', 'Puede consultar estado en DIAN')],
            },
        ),
        migrations.CreateModel(
            name='EventoDian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_evento', models.CharField(max_length=10, verbose_name='Código de Respuesta')),
                ('descripcion', models.TextField(verbose_name='Descripción del Evento')),
                ('xml_evento', models.TextField(blank=True, null=True, verbose_name='XML del Evento (ApplicationResponse)')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('es_error', models.BooleanField(default=False, verbose_name='Es Error')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Detalles Adicionales')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fiscal.facturaelectronica', verbose_name='Factura Electrónica')),
            ],
            options={
                'verbose_name': 'Evento DIAN',
                'verbose_name_plural': 'Eventos DIAN',
                'db_table': 'fiscal_evento_dian',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
