# Generated by Django 6.0 on 2026-01-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_facturaelectronica_eventodian'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_emisor', models.CharField(help_text='Sin dígito de verificación', max_length=20, verbose_name='NIT Emisor')),
                ('dv_emisor', models.CharField(max_length=1, verbose_name='Dígito Verificación')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('software_id', models.CharField(help_text='Proporcionado por la DIAN', max_length=100, verbose_name='ID Software')),
                ('pin_software', models.CharField(help_text='Para calcular la SoftwareSecurityCode', max_length=100, verbose_name='PIN Software')),
                ('ambiente', models.IntegerField(choices=[(1, 'Producción'), (2, 'Habilitación (Pruebas)')], default=2)),
                ('test_set_id', models.CharField(blank=True, help_text='Solo para habilitación', max_length=255, null=True, verbose_name='Test Set ID')),
                ('certificado_archivo', models.FileField(help_text='Archivo .p12 o .pfx', upload_to='fiscal/certs/')),
                ('_certificado_password', models.CharField(max_length=512, verbose_name='Contraseña Certificado (Encriptada)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración Fiscal DIAN',
                'verbose_name_plural': 'Configuraciones Fiscales',
            },
        ),
    ]
