# Generated by Django 6.0 on 2026-01-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_fiscalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(help_text='Ej: 890900943-1', max_length=20, unique=True, verbose_name='NIT')),
                ('name', models.CharField(help_text='Ej: ALKONPRAR', max_length=255, verbose_name='Razón Social')),
                ('commercial_name', models.CharField(blank=True, help_text='Ej: ALKONPRAR NEIVA', max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo visible en factura', max_length=254, verbose_name='Correo Electrónico')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('regimen', models.CharField(default='Responsable de IVA', max_length=100, verbose_name='Régimen')),
                ('dian_resolution', models.CharField(help_text='Ej: Resoluc. 000200 DIC. 27 de 2024', max_length=255, verbose_name='Texto Resolución')),
                ('dian_resolution_date', models.DateField(verbose_name='Fecha Resolución')),
                ('resolution_number', models.CharField(help_text='Ej: 0008327', max_length=50, verbose_name='Número Resolución')),
                ('prefix', models.CharField(help_text='Ej: X429', max_length=10, verbose_name='Prefijo')),
                ('number_from', models.BigIntegerField(verbose_name='Rango Desde')),
                ('number_to', models.BigIntegerField(verbose_name='Rango Hasta')),
                ('software_provider', models.CharField(help_text='Ej: FYM TECHNOLOGY S.A.S', max_length=255, verbose_name='Proveedor Tecnológico')),
                ('software_provider_nit', models.CharField(max_length=50, verbose_name='NIT Proveedor')),
                ('software_name', models.CharField(help_text='Ej: FAN eBill', max_length=100, verbose_name='Nombre Software')),
                ('iva_withholder', models.BooleanField(default=False, verbose_name='Agente de Retención IVA')),
                ('income_withholder', models.BooleanField(default=False, verbose_name='Agente de Retención Renta')),
                ('ica_exempt', models.BooleanField(default=False, verbose_name='Exento de ICA')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa (Resolución DIAN)',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
