# Generated by Django 6.0 on 2026-01-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='clave_tecnica',
            field=models.CharField(default='fc8eac422eba16e22ffd8c6f94b3f40a6e38162c', max_length=255, verbose_name='Clave Técnica'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Resolución'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='numero_resolucion',
            field=models.CharField(default='18760000001', max_length=50, verbose_name='Num. Resolución'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='prefijo',
            field=models.CharField(default='SETP', max_length=10, verbose_name='Prefijo'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='rango_desde',
            field=models.BigIntegerField(default=99000000, verbose_name='Rango Desde'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='rango_hasta',
            field=models.BigIntegerField(default=99500000, verbose_name='Rango Hasta'),
        ),
    ]
