# Generated by Django 6.0 on 2026-01-01 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_delete_company_fiscalconfig_clave_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fiscal/pdf/%Y/%m/', verbose_name='PDF Representación Gráfica'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='fiscal/xml/firmados/%Y/%m/', verbose_name='XML Firmado'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('generada', 'Generada'), ('firmada', 'Firmada'), ('enviada', 'Enviada a DIAN'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Número completo de factura (Prefijo + Consecutivo)', max_length=50, null=True, unique=True, verbose_name='Número de Factura'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='prefijo',
            field=models.CharField(blank=True, help_text='Prefijo del rango de numeración', max_length=10, null=True, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='estado_dian',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('GENERADO', 'XML Generado'), ('FIRMADO', 'XML Firmado'), ('ENVIADO', 'Enviado a DIAN'), ('ACEPTADO', 'Aceptado por DIAN'), ('RECHAZADO', 'Rechazado por DIAN'), ('ERROR', 'Error Técnico')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado DIAN (Detallado)'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='xml_firmado',
            field=models.FileField(blank=True, null=True, upload_to='fiscal/xml/firmados/%Y/%m/', verbose_name='XML Firmado (Legacy)'),
        ),
        migrations.CreateModel(
            name='RangoNumeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(help_text='Número de resolución otorgado por la DIAN', max_length=50, verbose_name='Número de Resolución')),
                ('fecha_resolucion', models.DateField(help_text='Fecha de emisión de la resolución', verbose_name='Fecha de Resolución')),
                ('fecha_inicio_vigencia', models.DateField(help_text='Fecha desde la cual se puede usar este rango', verbose_name='Fecha Inicio Vigencia')),
                ('fecha_fin_vigencia', models.DateField(help_text='Fecha hasta la cual es válido este rango', verbose_name='Fecha Fin Vigencia')),
                ('prefijo', models.CharField(help_text='Prefijo de facturación (ej: SETP, FE, FACT)', max_length=10, verbose_name='Prefijo')),
                ('rango_desde', models.BigIntegerField(help_text='Número inicial del rango autorizado', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rango Desde')),
                ('rango_hasta', models.BigIntegerField(help_text='Número final del rango autorizado', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rango Hasta')),
                ('consecutivo_actual', models.BigIntegerField(help_text='Próximo número a asignar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Consecutivo Actual')),
                ('clave_tecnica', models.CharField(help_text='Clave técnica proporcionada por la DIAN para este rango', max_length=255, verbose_name='Clave Técnica')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('is_default', models.BooleanField(default=False, help_text='Si está activo, se usará este rango automáticamente', verbose_name='Rango por Defecto')),
                ('porcentaje_alerta', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Porcentaje de uso para enviar alerta de agotamiento', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MinValueValidator(Decimal('100'))], verbose_name='Porcentaje de Alerta')),
                ('alerta_enviada', models.BooleanField(default=False, help_text='Indica si ya se envió la alerta de agotamiento', verbose_name='Alerta Enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre este rango', verbose_name='Notas')),
                ('fiscal_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rangos_numeracion', to='fiscal.fiscalconfig', verbose_name='Configuración Fiscal')),
            ],
            options={
                'verbose_name': 'Rango de Numeración',
                'verbose_name_plural': 'Rangos de Numeración',
                'db_table': 'fiscal_rango_numeracion',
                'ordering': ['-is_default', '-fecha_inicio_vigencia'],
                'indexes': [models.Index(fields=['estado', 'is_default'], name='fiscal_rang_estado_6e57c0_idx'), models.Index(fields=['prefijo', 'estado'], name='fiscal_rang_prefijo_d77853_idx')],
            },
        ),
    ]
