# Generated by Django 6.0 on 2026-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_alter_facturaelectronica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('generada', 'Generada'), ('firmada', 'Firmada'), ('enviada', 'Enviada a DIAN'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
